# ansible/site.yml

---
- hosts: rails
  remote_user: sreeram
  become: yes
  roles: 
    - common
    - ruby
    - role: node
      become: true
      become_user: "{{ user }}"
    - yarn
    - puma
    - nginx



